// var faker = require("faker");
// const mongoose = require("mongoose");

// const data = [
//   {
//     vehicle_oem_name: "Honda",
//     vehicle_model_name: "Durango",
//     year_of_launch: "2023-06-30T13:40:08.268Z",
//     vehicle_ex_showroom_price: "240.00",
//     vehicle_available_colors: "indigo",
//     vehicle_mileage: "5",
//     vehicle_power: 74059,
//     vehicle_max_speed: 10497,
//     _id: "1",
//   },
//   {
//     vehicle_oem_name: "Smart",
//     vehicle_model_name: "El Camino",
//     year_of_launch: "2023-06-19T09:07:01.059Z",
//     vehicle_ex_showroom_price: "749.00",
//     vehicle_available_colors: "pink",
//     vehicle_mileage: "6",
//     vehicle_power: 29751,
//     vehicle_max_speed: 88324,
//     _id: "2",
//   },
//   {
//     vehicle_oem_name: "Mercedes Benz",
//     vehicle_model_name: "ATS",
//     year_of_launch: "2022-12-16T02:29:59.040Z",
//     vehicle_ex_showroom_price: "62.00",
//     vehicle_available_colors: "silver",
//     vehicle_mileage: "9",
//     vehicle_power: 53626,
//     vehicle_max_speed: 93909,
//     _id: "3",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "CX-9",
//     year_of_launch: "2022-10-22T16:02:15.455Z",
//     vehicle_ex_showroom_price: "932.00",
//     vehicle_available_colors: "fuchsia",
//     vehicle_mileage: "7",
//     vehicle_power: 90240,
//     vehicle_max_speed: 68423,
//     _id: "4",
//   },
//   {
//     vehicle_oem_name: "BMW",
//     vehicle_model_name: "Camry",
//     year_of_launch: "2022-07-25T18:23:10.180Z",
//     vehicle_ex_showroom_price: "285.00",
//     vehicle_available_colors: "magenta",
//     vehicle_mileage: "1",
//     vehicle_power: 34330,
//     vehicle_max_speed: 3047,
//     _id: "5",
//   },
//   {
//     vehicle_oem_name: "Mercedes Benz",
//     vehicle_model_name: "Model T",
//     year_of_launch: "2022-09-09T02:48:32.603Z",
//     vehicle_ex_showroom_price: "365.00",
//     vehicle_available_colors: "salmon",
//     vehicle_mileage: "9",
//     vehicle_power: 92807,
//     vehicle_max_speed: 82370,
//     _id: "6",
//   },
//   {
//     vehicle_oem_name: "Porsche",
//     vehicle_model_name: "Model X",
//     year_of_launch: "2023-06-07T21:36:18.267Z",
//     vehicle_ex_showroom_price: "593.00",
//     vehicle_available_colors: "blue",
//     vehicle_mileage: "8",
//     vehicle_power: 43077,
//     vehicle_max_speed: 95893,
//     _id: "7",
//   },
//   {
//     vehicle_oem_name: "Smart",
//     vehicle_model_name: "Mustang",
//     year_of_launch: "2023-07-06T14:57:15.288Z",
//     vehicle_ex_showroom_price: "476.00",
//     vehicle_available_colors: "violet",
//     vehicle_mileage: "9",
//     vehicle_power: 24888,
//     vehicle_max_speed: 46003,
//     _id: "8",
//   },
//   {
//     vehicle_oem_name: "Volkswagen",
//     vehicle_model_name: "Model T",
//     year_of_launch: "2022-07-29T04:28:30.374Z",
//     vehicle_ex_showroom_price: "630.00",
//     vehicle_available_colors: "yellow",
//     vehicle_mileage: "3",
//     vehicle_power: 12724,
//     vehicle_max_speed: 43099,
//     _id: "9",
//   },
//   {
//     vehicle_oem_name: "Kia",
//     vehicle_model_name: "Cruze",
//     year_of_launch: "2022-08-02T07:17:16.537Z",
//     vehicle_ex_showroom_price: "427.00",
//     vehicle_available_colors: "pink",
//     vehicle_mileage: "7",
//     vehicle_power: 47168,
//     vehicle_max_speed: 62579,
//     _id: "10",
//   },
//   {
//     vehicle_oem_name: "BMW",
//     vehicle_model_name: "V90",
//     year_of_launch: "2022-09-12T11:42:26.049Z",
//     vehicle_ex_showroom_price: "236.00",
//     vehicle_available_colors: "tan",
//     vehicle_mileage: "9",
//     vehicle_power: 12755,
//     vehicle_max_speed: 66754,
//     _id: "11",
//   },
//   {
//     vehicle_oem_name: "Mazda",
//     vehicle_model_name: "Model Y",
//     year_of_launch: "2022-12-04T01:41:56.699Z",
//     vehicle_ex_showroom_price: "420.00",
//     vehicle_available_colors: "tan",
//     vehicle_mileage: "6",
//     vehicle_power: 40591,
//     vehicle_max_speed: 14131,
//     _id: "12",
//   },
//   {
//     vehicle_oem_name: "Bugatti",
//     vehicle_model_name: "Camry",
//     year_of_launch: "2023-01-21T14:18:10.968Z",
//     vehicle_ex_showroom_price: "684.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "6",
//     vehicle_power: 46964,
//     vehicle_max_speed: 6130,
//     _id: "13",
//   },
//   {
//     vehicle_oem_name: "Volkswagen",
//     vehicle_model_name: "V90",
//     year_of_launch: "2022-08-06T02:18:03.707Z",
//     vehicle_ex_showroom_price: "810.00",
//     vehicle_available_colors: "blue",
//     vehicle_mileage: "2",
//     vehicle_power: 66860,
//     vehicle_max_speed: 70022,
//     _id: "14",
//   },
//   {
//     vehicle_oem_name: "Hyundai",
//     vehicle_model_name: "Alpine",
//     year_of_launch: "2023-05-08T06:10:35.518Z",
//     vehicle_ex_showroom_price: "490.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "4",
//     vehicle_power: 99341,
//     vehicle_max_speed: 25233,
//     _id: "15",
//   },
//   {
//     vehicle_oem_name: "Mini",
//     vehicle_model_name: "Ranchero",
//     year_of_launch: "2022-12-30T12:15:17.694Z",
//     vehicle_ex_showroom_price: "692.00",
//     vehicle_available_colors: "teal",
//     vehicle_mileage: "7",
//     vehicle_power: 19155,
//     vehicle_max_speed: 26878,
//     _id: "16",
//   },
//   {
//     vehicle_oem_name: "Mazda",
//     vehicle_model_name: "Fiesta",
//     year_of_launch: "2022-08-18T14:34:36.767Z",
//     vehicle_ex_showroom_price: "862.00",
//     vehicle_available_colors: "plum",
//     vehicle_mileage: "6",
//     vehicle_power: 32268,
//     vehicle_max_speed: 54377,
//     _id: "17",
//   },
//   {
//     vehicle_oem_name: "Mazda",
//     vehicle_model_name: "Durango",
//     year_of_launch: "2023-07-08T15:51:14.035Z",
//     vehicle_ex_showroom_price: "183.00",
//     vehicle_available_colors: "azure",
//     vehicle_mileage: "6",
//     vehicle_power: 82725,
//     vehicle_max_speed: 92248,
//     _id: "18",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "Expedition",
//     year_of_launch: "2023-03-24T06:04:42.172Z",
//     vehicle_ex_showroom_price: "1.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "5",
//     vehicle_power: 67803,
//     vehicle_max_speed: 50919,
//     _id: "19",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "Colorado",
//     year_of_launch: "2023-02-10T09:02:31.051Z",
//     vehicle_ex_showroom_price: "382.00",
//     vehicle_available_colors: "magenta",
//     vehicle_mileage: "9",
//     vehicle_power: 53734,
//     vehicle_max_speed: 6173,
//     _id: "20",
//   },
//   {
//     vehicle_oem_name: "Bentley",
//     vehicle_model_name: "Model T",
//     year_of_launch: "2022-12-28T01:54:55.191Z",
//     vehicle_ex_showroom_price: "591.00",
//     vehicle_available_colors: "turquoise",
//     vehicle_mileage: "1",
//     vehicle_power: 37729,
//     vehicle_max_speed: 3247,
//     _id: "21",
//   },
//   {
//     vehicle_oem_name: "Jeep",
//     vehicle_model_name: "Grand Cherokee",
//     year_of_launch: "2023-01-03T14:15:14.572Z",
//     vehicle_ex_showroom_price: "721.00",
//     vehicle_available_colors: "lime",
//     vehicle_mileage: "3",
//     vehicle_power: 3810,
//     vehicle_max_speed: 25852,
//     _id: "22",
//   },
//   {
//     vehicle_oem_name: "Hyundai",
//     vehicle_model_name: "Countach",
//     year_of_launch: "2022-07-24T14:50:56.164Z",
//     vehicle_ex_showroom_price: "170.00",
//     vehicle_available_colors: "orchid",
//     vehicle_mileage: "3",
//     vehicle_power: 64715,
//     vehicle_max_speed: 75828,
//     _id: "23",
//   },
//   {
//     vehicle_oem_name: "Ford",
//     vehicle_model_name: "LeBaron",
//     year_of_launch: "2023-05-18T14:48:27.558Z",
//     vehicle_ex_showroom_price: "197.00",
//     vehicle_available_colors: "ivory",
//     vehicle_mileage: "6",
//     vehicle_power: 65488,
//     vehicle_max_speed: 52659,
//     _id: "24",
//   },
//   {
//     vehicle_oem_name: "Mercedes Benz",
//     vehicle_model_name: "Grand Caravan",
//     year_of_launch: "2023-02-26T11:58:46.081Z",
//     vehicle_ex_showroom_price: "144.00",
//     vehicle_available_colors: "yellow",
//     vehicle_mileage: "3",
//     vehicle_power: 43975,
//     vehicle_max_speed: 28606,
//     _id: "25",
//   },
//   {
//     vehicle_oem_name: "Land Rover",
//     vehicle_model_name: "Challenger",
//     year_of_launch: "2023-01-06T19:03:39.727Z",
//     vehicle_ex_showroom_price: "542.00",
//     vehicle_available_colors: "salmon",
//     vehicle_mileage: "3",
//     vehicle_power: 496,
//     vehicle_max_speed: 46245,
//     _id: "26",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "Cruze",
//     year_of_launch: "2022-11-26T22:24:55.570Z",
//     vehicle_ex_showroom_price: "466.00",
//     vehicle_available_colors: "maroon",
//     vehicle_mileage: "7",
//     vehicle_power: 591,
//     vehicle_max_speed: 85563,
//     _id: "27",
//   },
//   {
//     vehicle_oem_name: "Kia",
//     vehicle_model_name: "Altima",
//     year_of_launch: "2022-07-23T05:41:55.649Z",
//     vehicle_ex_showroom_price: "59.00",
//     vehicle_available_colors: "magenta",
//     vehicle_mileage: "6",
//     vehicle_power: 40061,
//     vehicle_max_speed: 56811,
//     _id: "28",
//   },
//   {
//     vehicle_oem_name: "Lamborghini",
//     vehicle_model_name: "2",
//     year_of_launch: "2023-06-10T12:15:59.535Z",
//     vehicle_ex_showroom_price: "848.00",
//     vehicle_available_colors: "yellow",
//     vehicle_mileage: "7",
//     vehicle_power: 41474,
//     vehicle_max_speed: 4102,
//     _id: "29",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "Taurus",
//     year_of_launch: "2022-08-12T10:53:50.353Z",
//     vehicle_ex_showroom_price: "692.00",
//     vehicle_available_colors: "blue",
//     vehicle_mileage: "6",
//     vehicle_power: 13537,
//     vehicle_max_speed: 84100,
//     _id: "30",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "Prius",
//     year_of_launch: "2023-02-20T22:03:44.265Z",
//     vehicle_ex_showroom_price: "709.00",
//     vehicle_available_colors: "olive",
//     vehicle_mileage: "4",
//     vehicle_power: 43380,
//     vehicle_max_speed: 1537,
//     _id: "31",
//   },
//   {
//     vehicle_oem_name: "Volvo",
//     vehicle_model_name: "Land Cruiser",
//     year_of_launch: "2023-03-10T03:42:21.298Z",
//     vehicle_ex_showroom_price: "751.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "9",
//     vehicle_power: 72131,
//     vehicle_max_speed: 92964,
//     _id: "32",
//   },
//   {
//     vehicle_oem_name: "Tesla",
//     vehicle_model_name: "El Camino",
//     year_of_launch: "2022-09-20T07:34:42.323Z",
//     vehicle_ex_showroom_price: "326.00",
//     vehicle_available_colors: "blue",
//     vehicle_mileage: "2",
//     vehicle_power: 58966,
//     vehicle_max_speed: 43877,
//     _id: "33",
//   },
//   {
//     vehicle_oem_name: "Fiat",
//     vehicle_model_name: "V90",
//     year_of_launch: "2022-09-28T12:09:23.422Z",
//     vehicle_ex_showroom_price: "664.00",
//     vehicle_available_colors: "violet",
//     vehicle_mileage: "6",
//     vehicle_power: 33816,
//     vehicle_max_speed: 29023,
//     _id: "34",
//   },
//   {
//     vehicle_oem_name: "Polestar",
//     vehicle_model_name: "El Camino",
//     year_of_launch: "2023-04-06T09:47:41.329Z",
//     vehicle_ex_showroom_price: "700.00",
//     vehicle_available_colors: "salmon",
//     vehicle_mileage: "6",
//     vehicle_power: 39718,
//     vehicle_max_speed: 4206,
//     _id: "35",
//   },
//   {
//     vehicle_oem_name: "Ford",
//     vehicle_model_name: "Cruze",
//     year_of_launch: "2022-12-16T00:09:01.404Z",
//     vehicle_ex_showroom_price: "747.00",
//     vehicle_available_colors: "gold",
//     vehicle_mileage: "2",
//     vehicle_power: 41077,
//     vehicle_max_speed: 95188,
//     _id: "36",
//   },
//   {
//     vehicle_oem_name: "Nissan",
//     vehicle_model_name: "911",
//     year_of_launch: "2023-05-20T08:25:44.329Z",
//     vehicle_ex_showroom_price: "784.00",
//     vehicle_available_colors: "white",
//     vehicle_mileage: "8",
//     vehicle_power: 10075,
//     vehicle_max_speed: 34192,
//     _id: "37",
//   },
//   {
//     vehicle_oem_name: "Polestar",
//     vehicle_model_name: "Model S",
//     year_of_launch: "2023-01-06T08:23:08.800Z",
//     vehicle_ex_showroom_price: "495.00",
//     vehicle_available_colors: "orange",
//     vehicle_mileage: "2",
//     vehicle_power: 68965,
//     vehicle_max_speed: 81712,
//     _id: "38",
//   },
//   {
//     vehicle_oem_name: "Lamborghini",
//     vehicle_model_name: "A4",
//     year_of_launch: "2022-12-26T01:39:11.190Z",
//     vehicle_ex_showroom_price: "249.00",
//     vehicle_available_colors: "ivory",
//     vehicle_mileage: "2",
//     vehicle_power: 50358,
//     vehicle_max_speed: 6727,
//     _id: "39",
//   },
//   {
//     vehicle_oem_name: "Land Rover",
//     vehicle_model_name: "Ranchero",
//     year_of_launch: "2023-01-05T04:37:49.218Z",
//     vehicle_ex_showroom_price: "785.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "5",
//     vehicle_power: 84501,
//     vehicle_max_speed: 64890,
//     _id: "40",
//   },
//   {
//     vehicle_oem_name: "Audi",
//     vehicle_model_name: "Land Cruiser",
//     year_of_launch: "2023-04-21T15:08:33.598Z",
//     vehicle_ex_showroom_price: "9.00",
//     vehicle_available_colors: "purple",
//     vehicle_mileage: "1",
//     vehicle_power: 66199,
//     vehicle_max_speed: 66639,
//     _id: "41",
//   },
//   {
//     vehicle_oem_name: "Mazda",
//     vehicle_model_name: "Focus",
//     year_of_launch: "2022-10-01T14:44:12.727Z",
//     vehicle_ex_showroom_price: "222.00",
//     vehicle_available_colors: "teal",
//     vehicle_mileage: "6",
//     vehicle_power: 52013,
//     vehicle_max_speed: 14494,
//     _id: "42",
//   },
//   {
//     vehicle_oem_name: "Volvo",
//     vehicle_model_name: "Focus",
//     year_of_launch: "2023-07-10T13:39:44.048Z",
//     vehicle_ex_showroom_price: "818.00",
//     vehicle_available_colors: "magenta",
//     vehicle_mileage: "9",
//     vehicle_power: 66910,
//     vehicle_max_speed: 50313,
//     _id: "43",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "Model S",
//     year_of_launch: "2023-01-14T22:40:58.890Z",
//     vehicle_ex_showroom_price: "773.00",
//     vehicle_available_colors: "gold",
//     vehicle_mileage: "2",
//     vehicle_power: 51956,
//     vehicle_max_speed: 42149,
//     _id: "44",
//   },
//   {
//     vehicle_oem_name: "Mercedes Benz",
//     vehicle_model_name: "Taurus",
//     year_of_launch: "2022-09-30T18:54:33.177Z",
//     vehicle_ex_showroom_price: "315.00",
//     vehicle_available_colors: "cyan",
//     vehicle_mileage: "1",
//     vehicle_power: 78049,
//     vehicle_max_speed: 25473,
//     _id: "45",
//   },
//   {
//     vehicle_oem_name: "Land Rover",
//     vehicle_model_name: "Countach",
//     year_of_launch: "2022-11-20T02:53:31.972Z",
//     vehicle_ex_showroom_price: "737.00",
//     vehicle_available_colors: "ivory",
//     vehicle_mileage: "2",
//     vehicle_power: 85901,
//     vehicle_max_speed: 9046,
//     _id: "46",
//   },
//   {
//     vehicle_oem_name: "Nissan",
//     vehicle_model_name: "Sentra",
//     year_of_launch: "2023-03-25T06:34:03.112Z",
//     vehicle_ex_showroom_price: "295.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "6",
//     vehicle_power: 99594,
//     vehicle_max_speed: 64060,
//     _id: "47",
//   },
//   {
//     vehicle_oem_name: "Porsche",
//     vehicle_model_name: "Impala",
//     year_of_launch: "2022-09-19T03:13:40.179Z",
//     vehicle_ex_showroom_price: "774.00",
//     vehicle_available_colors: "violet",
//     vehicle_mileage: "8",
//     vehicle_power: 72837,
//     vehicle_max_speed: 63760,
//     _id: "48",
//   },
//   {
//     vehicle_oem_name: "Mazda",
//     vehicle_model_name: "Explorer",
//     year_of_launch: "2023-06-10T21:39:47.882Z",
//     vehicle_ex_showroom_price: "410.00",
//     vehicle_available_colors: "white",
//     vehicle_mileage: "6",
//     vehicle_power: 93504,
//     vehicle_max_speed: 49454,
//     _id: "49",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "Taurus",
//     year_of_launch: "2023-04-17T11:30:14.188Z",
//     vehicle_ex_showroom_price: "771.00",
//     vehicle_available_colors: "plum",
//     vehicle_mileage: "9",
//     vehicle_power: 32031,
//     vehicle_max_speed: 35779,
//     _id: "50",
//   },
//   {
//     vehicle_oem_name: "Jeep",
//     vehicle_model_name: "Expedition",
//     year_of_launch: "2023-07-17T13:53:12.427Z",
//     vehicle_ex_showroom_price: "245.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "3",
//     vehicle_power: 75450,
//     vehicle_max_speed: 45382,
//     _id: "51",
//   },
//   {
//     vehicle_oem_name: "Volvo",
//     vehicle_model_name: "Explorer",
//     year_of_launch: "2022-08-05T16:28:04.743Z",
//     vehicle_ex_showroom_price: "416.00",
//     vehicle_available_colors: "lime",
//     vehicle_mileage: "9",
//     vehicle_power: 71638,
//     vehicle_max_speed: 62339,
//     _id: "52",
//   },
//   {
//     vehicle_oem_name: "Dodge",
//     vehicle_model_name: "Model X",
//     year_of_launch: "2023-05-14T01:09:02.377Z",
//     vehicle_ex_showroom_price: "221.00",
//     vehicle_available_colors: "mint green",
//     vehicle_mileage: "9",
//     vehicle_power: 14903,
//     vehicle_max_speed: 70487,
//     _id: "53",
//   },
//   {
//     vehicle_oem_name: "Nissan",
//     vehicle_model_name: "Civic",
//     year_of_launch: "2023-04-05T04:58:41.520Z",
//     vehicle_ex_showroom_price: "491.00",
//     vehicle_available_colors: "indigo",
//     vehicle_mileage: "6",
//     vehicle_power: 30281,
//     vehicle_max_speed: 73638,
//     _id: "54",
//   },
//   {
//     vehicle_oem_name: "Polestar",
//     vehicle_model_name: "Ranchero",
//     year_of_launch: "2023-01-25T13:19:35.925Z",
//     vehicle_ex_showroom_price: "175.00",
//     vehicle_available_colors: "maroon",
//     vehicle_mileage: "6",
//     vehicle_power: 35933,
//     vehicle_max_speed: 25494,
//     _id: "55",
//   },
//   {
//     vehicle_oem_name: "Lamborghini",
//     vehicle_model_name: "2",
//     year_of_launch: "2023-05-22T15:17:55.154Z",
//     vehicle_ex_showroom_price: "365.00",
//     vehicle_available_colors: "orchid",
//     vehicle_mileage: "5",
//     vehicle_power: 87017,
//     vehicle_max_speed: 70929,
//     _id: "56",
//   },
//   {
//     vehicle_oem_name: "Kia",
//     vehicle_model_name: "Charger",
//     year_of_launch: "2022-10-04T02:28:14.138Z",
//     vehicle_ex_showroom_price: "222.00",
//     vehicle_available_colors: "yellow",
//     vehicle_mileage: "8",
//     vehicle_power: 52538,
//     vehicle_max_speed: 9057,
//     _id: "57",
//   },
//   {
//     vehicle_oem_name: "Rolls Royce",
//     vehicle_model_name: "Impala",
//     year_of_launch: "2023-04-03T08:45:47.938Z",
//     vehicle_ex_showroom_price: "220.00",
//     vehicle_available_colors: "sky blue",
//     vehicle_mileage: "4",
//     vehicle_power: 58381,
//     vehicle_max_speed: 17519,
//     _id: "58",
//   },
//   {
//     vehicle_oem_name: "Nissan",
//     vehicle_model_name: "XC90",
//     year_of_launch: "2023-01-22T14:32:02.421Z",
//     vehicle_ex_showroom_price: "151.00",
//     vehicle_available_colors: "silver",
//     vehicle_mileage: "7",
//     vehicle_power: 30007,
//     vehicle_max_speed: 25121,
//     _id: "59",
//   },
//   {
//     vehicle_oem_name: "Nissan",
//     vehicle_model_name: "Malibu",
//     year_of_launch: "2023-06-07T12:17:36.676Z",
//     vehicle_ex_showroom_price: "937.00",
//     vehicle_available_colors: "maroon",
//     vehicle_mileage: "7",
//     vehicle_power: 1405,
//     vehicle_max_speed: 39783,
//     _id: "60",
//   },
//   {
//     vehicle_oem_name: "Jaguar",
//     vehicle_model_name: "Challenger",
//     year_of_launch: "2023-02-24T12:32:52.058Z",
//     vehicle_ex_showroom_price: "765.00",
//     vehicle_available_colors: "ivory",
//     vehicle_mileage: "3",
//     vehicle_power: 52152,
//     vehicle_max_speed: 99322,
//     _id: "61",
//   },
//   {
//     vehicle_oem_name: "Lamborghini",
//     vehicle_model_name: "911",
//     year_of_launch: "2022-11-25T12:50:11.187Z",
//     vehicle_ex_showroom_price: "532.00",
//     vehicle_available_colors: "orchid",
//     vehicle_mileage: "2",
//     vehicle_power: 25261,
//     vehicle_max_speed: 105,
//     _id: "62",
//   },
//   {
//     vehicle_oem_name: "Chrysler",
//     vehicle_model_name: "LeBaron",
//     year_of_launch: "2023-04-10T21:28:26.673Z",
//     vehicle_ex_showroom_price: "486.00",
//     vehicle_available_colors: "white",
//     vehicle_mileage: "8",
//     vehicle_power: 58034,
//     vehicle_max_speed: 52671,
//     _id: "63",
//   },
//   {
//     vehicle_oem_name: "Tesla",
//     vehicle_model_name: "PT Cruiser",
//     year_of_launch: "2023-04-19T20:10:55.063Z",
//     vehicle_ex_showroom_price: "541.00",
//     vehicle_available_colors: "salmon",
//     vehicle_mileage: "2",
//     vehicle_power: 24846,
//     vehicle_max_speed: 28705,
//     _id: "64",
//   },
//   {
//     vehicle_oem_name: "Chrysler",
//     vehicle_model_name: "Model S",
//     year_of_launch: "2023-05-08T16:59:28.484Z",
//     vehicle_ex_showroom_price: "309.00",
//     vehicle_available_colors: "orange",
//     vehicle_mileage: "4",
//     vehicle_power: 19730,
//     vehicle_max_speed: 18157,
//     _id: "65",
//   },
//   {
//     vehicle_oem_name: "Chevrolet",
//     vehicle_model_name: "Grand Cherokee",
//     year_of_launch: "2023-02-17T07:28:28.680Z",
//     vehicle_ex_showroom_price: "154.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "7",
//     vehicle_power: 27484,
//     vehicle_max_speed: 36458,
//     _id: "66",
//   },
//   {
//     vehicle_oem_name: "Bugatti",
//     vehicle_model_name: "Jetta",
//     year_of_launch: "2023-02-07T08:36:35.297Z",
//     vehicle_ex_showroom_price: "517.00",
//     vehicle_available_colors: "indigo",
//     vehicle_mileage: "1",
//     vehicle_power: 78415,
//     vehicle_max_speed: 97688,
//     _id: "67",
//   },
//   {
//     vehicle_oem_name: "Toyota",
//     vehicle_model_name: "Grand Cherokee",
//     year_of_launch: "2022-08-13T02:42:09.223Z",
//     vehicle_ex_showroom_price: "630.00",
//     vehicle_available_colors: "cyan",
//     vehicle_mileage: "9",
//     vehicle_power: 74365,
//     vehicle_max_speed: 80035,
//     _id: "68",
//   },
//   {
//     vehicle_oem_name: "Mercedes Benz",
//     vehicle_model_name: "PT Cruiser",
//     year_of_launch: "2023-01-05T01:03:53.174Z",
//     vehicle_ex_showroom_price: "70.00",
//     vehicle_available_colors: "olive",
//     vehicle_mileage: "6",
//     vehicle_power: 4585,
//     vehicle_max_speed: 68107,
//     _id: "69",
//   },
//   {
//     vehicle_oem_name: "Polestar",
//     vehicle_model_name: "Beetle",
//     year_of_launch: "2022-11-24T22:23:44.302Z",
//     vehicle_ex_showroom_price: "569.00",
//     vehicle_available_colors: "violet",
//     vehicle_mileage: "4",
//     vehicle_power: 57853,
//     vehicle_max_speed: 20477,
//     _id: "70",
//   },
//   {
//     vehicle_oem_name: "Bentley",
//     vehicle_model_name: "Escalade",
//     year_of_launch: "2023-04-07T01:55:11.885Z",
//     vehicle_ex_showroom_price: "187.00",
//     vehicle_available_colors: "tan",
//     vehicle_mileage: "6",
//     vehicle_power: 92569,
//     vehicle_max_speed: 87572,
//     _id: "71",
//   },
//   {
//     vehicle_oem_name: "Nissan",
//     vehicle_model_name: "Corvette",
//     year_of_launch: "2023-02-14T11:13:50.033Z",
//     vehicle_ex_showroom_price: "317.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "9",
//     vehicle_power: 83997,
//     vehicle_max_speed: 40178,
//     _id: "72",
//   },
//   {
//     vehicle_oem_name: "Chevrolet",
//     vehicle_model_name: "Malibu",
//     year_of_launch: "2022-12-18T05:07:59.324Z",
//     vehicle_ex_showroom_price: "776.00",
//     vehicle_available_colors: "silver",
//     vehicle_mileage: "4",
//     vehicle_power: 45861,
//     vehicle_max_speed: 61632,
//     _id: "73",
//   },
//   {
//     vehicle_oem_name: "Smart",
//     vehicle_model_name: "Alpine",
//     year_of_launch: "2023-05-11T00:46:29.493Z",
//     vehicle_ex_showroom_price: "262.00",
//     vehicle_available_colors: "magenta",
//     vehicle_mileage: "8",
//     vehicle_power: 30332,
//     vehicle_max_speed: 7881,
//     _id: "74",
//   },
//   {
//     vehicle_oem_name: "Jeep",
//     vehicle_model_name: "Model Y",
//     year_of_launch: "2022-12-02T20:08:47.768Z",
//     vehicle_ex_showroom_price: "437.00",
//     vehicle_available_colors: "black",
//     vehicle_mileage: "1",
//     vehicle_power: 52367,
//     vehicle_max_speed: 63917,
//     _id: "75",
//   },
//   {
//     vehicle_oem_name: "Porsche",
//     vehicle_model_name: "Durango",
//     year_of_launch: "2023-04-09T23:53:47.607Z",
//     vehicle_ex_showroom_price: "169.00",
//     vehicle_available_colors: "sky blue",
//     vehicle_mileage: "1",
//     vehicle_power: 72716,
//     vehicle_max_speed: 38816,
//     _id: "76",
//   },
//   {
//     vehicle_oem_name: "Mazda",
//     vehicle_model_name: "F-150",
//     year_of_launch: "2022-10-20T13:17:20.154Z",
//     vehicle_ex_showroom_price: "427.00",
//     vehicle_available_colors: "indigo",
//     vehicle_mileage: "2",
//     vehicle_power: 76058,
//     vehicle_max_speed: 92778,
//     _id: "77",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "ATS",
//     year_of_launch: "2023-06-21T23:26:31.692Z",
//     vehicle_ex_showroom_price: "807.00",
//     vehicle_available_colors: "mint green",
//     vehicle_mileage: "2",
//     vehicle_power: 56163,
//     vehicle_max_speed: 63377,
//     _id: "78",
//   },
//   {
//     vehicle_oem_name: "Rolls Royce",
//     vehicle_model_name: "Fortwo",
//     year_of_launch: "2022-11-20T13:50:53.856Z",
//     vehicle_ex_showroom_price: "626.00",
//     vehicle_available_colors: "red",
//     vehicle_mileage: "9",
//     vehicle_power: 34753,
//     vehicle_max_speed: 95214,
//     _id: "79",
//   },
//   {
//     vehicle_oem_name: "Polestar",
//     vehicle_model_name: "CTS",
//     year_of_launch: "2023-04-15T19:47:27.704Z",
//     vehicle_ex_showroom_price: "497.00",
//     vehicle_available_colors: "olive",
//     vehicle_mileage: "7",
//     vehicle_power: 29487,
//     vehicle_max_speed: 99486,
//     _id: "80",
//   },
//   {
//     vehicle_oem_name: "Jeep",
//     vehicle_model_name: "ATS",
//     year_of_launch: "2022-10-12T20:47:51.737Z",
//     vehicle_ex_showroom_price: "185.00",
//     vehicle_available_colors: "orange",
//     vehicle_mileage: "3",
//     vehicle_power: 75960,
//     vehicle_max_speed: 36476,
//     _id: "81",
//   },
//   {
//     vehicle_oem_name: "Kia",
//     vehicle_model_name: "Countach",
//     year_of_launch: "2023-01-13T20:12:36.763Z",
//     vehicle_ex_showroom_price: "892.00",
//     vehicle_available_colors: "pink",
//     vehicle_mileage: "8",
//     vehicle_power: 32701,
//     vehicle_max_speed: 73397,
//     _id: "82",
//   },
//   {
//     vehicle_oem_name: "Mercedes Benz",
//     vehicle_model_name: "Fiesta",
//     year_of_launch: "2023-03-17T08:30:54.365Z",
//     vehicle_ex_showroom_price: "124.00",
//     vehicle_available_colors: "turquoise",
//     vehicle_mileage: "1",
//     vehicle_power: 70164,
//     vehicle_max_speed: 10042,
//     _id: "83",
//   },
//   {
//     vehicle_oem_name: "Kia",
//     vehicle_model_name: "CX-9",
//     year_of_launch: "2022-12-07T12:41:49.964Z",
//     vehicle_ex_showroom_price: "297.00",
//     vehicle_available_colors: "maroon",
//     vehicle_mileage: "5",
//     vehicle_power: 89178,
//     vehicle_max_speed: 92287,
//     _id: "84",
//   },
//   {
//     vehicle_oem_name: "Honda",
//     vehicle_model_name: "1",
//     year_of_launch: "2022-11-17T22:54:15.287Z",
//     vehicle_ex_showroom_price: "752.00",
//     vehicle_available_colors: "silver",
//     vehicle_mileage: "7",
//     vehicle_power: 63470,
//     vehicle_max_speed: 74973,
//     _id: "85",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "Grand Caravan",
//     year_of_launch: "2022-10-09T20:49:03.893Z",
//     vehicle_ex_showroom_price: "773.00",
//     vehicle_available_colors: "azure",
//     vehicle_mileage: "8",
//     vehicle_power: 74355,
//     vehicle_max_speed: 13244,
//     _id: "86",
//   },
//   {
//     vehicle_oem_name: "Dodge",
//     vehicle_model_name: "911",
//     year_of_launch: "2023-04-20T04:04:50.346Z",
//     vehicle_ex_showroom_price: "965.00",
//     vehicle_available_colors: "ivory",
//     vehicle_mileage: "6",
//     vehicle_power: 72007,
//     vehicle_max_speed: 5721,
//     _id: "87",
//   },
//   {
//     vehicle_oem_name: "Jeep",
//     vehicle_model_name: "F-150",
//     year_of_launch: "2023-04-04T09:51:52.994Z",
//     vehicle_ex_showroom_price: "960.00",
//     vehicle_available_colors: "cyan",
//     vehicle_mileage: "3",
//     vehicle_power: 84857,
//     vehicle_max_speed: 89782,
//     _id: "88",
//   },
//   {
//     vehicle_oem_name: "Aston Martin",
//     vehicle_model_name: "F-150",
//     year_of_launch: "2023-02-01T20:49:06.559Z",
//     vehicle_ex_showroom_price: "286.00",
//     vehicle_available_colors: "maroon",
//     vehicle_mileage: "7",
//     vehicle_power: 62184,
//     vehicle_max_speed: 97059,
//     _id: "89",
//   },
//   {
//     vehicle_oem_name: "Ford",
//     vehicle_model_name: "Model Y",
//     year_of_launch: "2022-08-21T04:11:12.163Z",
//     vehicle_ex_showroom_price: "49.00",
//     vehicle_available_colors: "salmon",
//     vehicle_mileage: "1",
//     vehicle_power: 58094,
//     vehicle_max_speed: 31257,
//     _id: "90",
//   },
//   {
//     vehicle_oem_name: "Volvo",
//     vehicle_model_name: "Model T",
//     year_of_launch: "2022-08-02T03:30:05.957Z",
//     vehicle_ex_showroom_price: "907.00",
//     vehicle_available_colors: "mint green",
//     vehicle_mileage: "9",
//     vehicle_power: 26963,
//     vehicle_max_speed: 33976,
//     _id: "91",
//   },
//   {
//     vehicle_oem_name: "Lamborghini",
//     vehicle_model_name: "Countach",
//     year_of_launch: "2023-05-28T21:32:07.399Z",
//     vehicle_ex_showroom_price: "557.00",
//     vehicle_available_colors: "orange",
//     vehicle_mileage: "2",
//     vehicle_power: 70061,
//     vehicle_max_speed: 26659,
//     _id: "92",
//   },
//   {
//     vehicle_oem_name: "Mazda",
//     vehicle_model_name: "Golf",
//     year_of_launch: "2022-12-08T02:29:55.123Z",
//     vehicle_ex_showroom_price: "208.00",
//     vehicle_available_colors: "cyan",
//     vehicle_mileage: "5",
//     vehicle_power: 63982,
//     vehicle_max_speed: 21681,
//     _id: "93",
//   },
//   {
//     vehicle_oem_name: "Honda",
//     vehicle_model_name: "Taurus",
//     year_of_launch: "2023-04-03T09:08:59.829Z",
//     vehicle_ex_showroom_price: "393.00",
//     vehicle_available_colors: "ivory",
//     vehicle_mileage: "3",
//     vehicle_power: 63003,
//     vehicle_max_speed: 85419,
//     _id: "94",
//   },
//   {
//     vehicle_oem_name: "Volvo",
//     vehicle_model_name: "Wrangler",
//     year_of_launch: "2023-03-31T03:04:29.416Z",
//     vehicle_ex_showroom_price: "392.00",
//     vehicle_available_colors: "orange",
//     vehicle_mileage: "8",
//     vehicle_power: 67672,
//     vehicle_max_speed: 57928,
//     _id: "95",
//   },
//   {
//     vehicle_oem_name: "Land Rover",
//     vehicle_model_name: "V90",
//     year_of_launch: "2023-03-27T14:31:36.739Z",
//     vehicle_ex_showroom_price: "850.00",
//     vehicle_available_colors: "orchid",
//     vehicle_mileage: "9",
//     vehicle_power: 98385,
//     vehicle_max_speed: 90058,
//     _id: "96",
//   },
//   {
//     vehicle_oem_name: "Fiat",
//     vehicle_model_name: "Charger",
//     year_of_launch: "2022-08-10T08:42:22.064Z",
//     vehicle_ex_showroom_price: "41.00",
//     vehicle_available_colors: "yellow",
//     vehicle_mileage: "9",
//     vehicle_power: 93515,
//     vehicle_max_speed: 67196,
//     _id: "97",
//   },
//   {
//     vehicle_oem_name: "Chrysler",
//     vehicle_model_name: "El Camino",
//     year_of_launch: "2022-08-14T02:18:31.892Z",
//     vehicle_ex_showroom_price: "383.00",
//     vehicle_available_colors: "plum",
//     vehicle_mileage: "3",
//     vehicle_power: 13100,
//     vehicle_max_speed: 16693,
//     _id: "98",
//   },
//   {
//     vehicle_oem_name: "Tesla",
//     vehicle_model_name: "Countach",
//     year_of_launch: "2022-10-05T03:28:35.976Z",
//     vehicle_ex_showroom_price: "237.00",
//     vehicle_available_colors: "magenta",
//     vehicle_mileage: "3",
//     vehicle_power: 14785,
//     vehicle_max_speed: 58799,
//     _id: "99",
//   },
//   {
//     vehicle_oem_name: "Polestar",
//     vehicle_model_name: "Taurus",
//     year_of_launch: "2023-01-24T13:23:04.471Z",
//     vehicle_ex_showroom_price: "90.00",
//     vehicle_available_colors: "blue",
//     vehicle_mileage: "6",
//     vehicle_power: 38099,
//     vehicle_max_speed: 87473,
//     _id: "100",
//   },
// ];
// const Schema = mongoose.Schema(
//   {
//     vehicle_oem_name: { type: String },
//     vehicle_model_name: { type: String, required: true },
//     year_of_launch: {
//       type: String,
//       required: true,
//     },
//     vehicle_ex_showroom_price: { type: Number, required: true },
//     vehicle_available_colors: {
//       type: [String],
//       enum: [
//         "Red",
//         "Blue",
//         "Green",
//         "Yellow",
//         "Black",
//         "White",
//         "Silver",
//         "Gray",
//         "Other",
//       ],
//       required: true,
//     },
//     vehicle_mileage: { type: Number, min: 0, required: true },
//     vehicle_power: { type: Number, min: 0, required: true },
//     vehicle_max_speed: { type: Number, min: 0, required: true },
//     image: { type: String },
//   },
//   {
//     versionKey: false,
//   }
// );
// function getRandomColors() {
//   const colors = [
//     "Red",
//     "Blue",
//     "Green",
//     "Yellow",
//     "Black",
//     "White",
//     "Silver",
//     "Gray",
//     "Other",
//   ];

//   const randomColors = [];
//   const maxIndex = colors.length - 1;

//   while (randomColors.length < 5) {
//     const randomIndex = Math.floor(Math.random() * (maxIndex + 1));
//     const randomColor = colors[randomIndex];
//     if (!randomColors.includes(randomColor)) {
//       randomColors.push(randomColor);
//     }
//   }

//   return randomColors;
// }

// const oemModel = mongoose.model("oem_specs", Schema);
// const currentYear = new Date().getFullYear();
// const generateDataset = async () => {
//   try {
//     await mongoose.connect(
//       "mongodb+srv://tathagat:tathagat@cluster0.xuzkcmo.mongodb.net/buycars?retryWrites=true&w=majority"
//     );

//     for (let i = 0; i < data.length - 1; i++) {
//       const vehicle = new oemModel({
//         vehicle_oem_name: data[i].vehicle_oem_name,
//         vehicle_model_name: `${data[i].vehicle_oem_name} ${
//           data[i].vehicle_model_name
//         } ${data[i].year_of_launch.split("-")[0]}`,
//         year_of_launch: data[i].year_of_launch.split("-")[0],
//         vehicle_ex_showroom_price: faker.random.number({
//           min: 50000,
//           max: 200000,
//         }),
//         vehicle_available_colors: getRandomColors(),
//         vehicle_mileage: faker.random.number({ min: 5, max: 15 }),
//         vehicle_power: faker.random.number({ min: 100, max: 500 }),
//         vehicle_max_speed: faker.random.number({ min: 150, max: 300 }),
//         image: "https://loremflickr.com/320/240/supercars",
//       });

//       await vehicle.save();
//     }

//     console.log("Fake data generated successfully.");

//     mongoose.disconnect();
//   } catch (error) {
//     console.error("Error generating fake data:", error);
//   }
// };

// generateDataset();
